services:
  db:
    container_name: my-playlist-db
    image: postgres
    environment:
      POSTGRES_DB: playlist-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    ports:
      - "5331:5432"
    networks:
      - db
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db: